[workspace]
members = ["front", "shared", "api"]

resolver = "2"

[workspace.package]
name = "power-scouter"
version = "0.2.0"
edition = "2021"
publish = false

[workspace.dependencies]
serde = { version = "1.0", features = ['derive'] }
serde_json = "1.0"
