[package]
name = "power-scouter"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]
members = [
  "front",
  "."
]

[lib]

[dependencies]
shuttle-service = { version = "0.11.0", features = ["web-actix-web"] }
actix-web = "4.3.1"
actix-files = "0.6.2"
serde = "1.0.152"
serde_json = "1.0.94"
shuttle-static-folder = "0.11.0"
tracing = "0.1.37"
