[tasks.shuttle]
workspace = false
env = { "RUST_LOG" = "trace" }
install_crate = "cargo-shuttle"
command = "cargo"
args = ["shuttle", "run"]

[tasks.serve]
workspace = false
script_runner = "@shell"
script = '''
cd front
dioxus serve
'''

[tasks.front]
workspace = false
script_runner = "@shell"
script = '''
cd front
dioxus build --release
mv static ../static
'''

[tasks.clippy]
workspace = false
install_crate = "cargo-clippy"
command = "cargo"
args = ["clippy"]

[tasks.format]
clear = true
workspace = false
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--all", "--", "--check"]
