[tasks.dev]
workspace = false
env = { "RUST_LOG" = "trace" }
command = "cargo"
args = ["run"]

[tasks.serve]
workspace = false
script_runner = "@shell"
script = '''
cd front
dx serve
'''

[tasks.front]
workspace = false
script_runner = "@shell"
script = '''
cd front
dx build --release
mv static ../static
'''

[tasks.clippy]
workspace = false
install_crate = "cargo-clippy"
command = "cargo"
args = ["clippy"]

[tasks.format]
clear = true
workspace = false
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--all", "--", "--check"]
