[package]
name = "api"
version = "0.2.0"
edition = "2021"
publish = false

[dependencies]
actix-web = "4.8"
tokio = "1.26.0"
actix-files = "0.6"
shared = { path = "../shared" }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = "0.1.40"
mime = "0.3.17"
