name: "Pull Request Build validation"
run-name: ${{ github.actor }} is building app helped by 🦀
on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
jobs:
  build_and_test:
    name: Build Frontend and API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          components: rustfmt, clippy
      - name: Install cargo-make
        uses: baptiste0928/cargo-install@v2
        with:
          crate: cargo-make
          version: "^0.36.5"
      - name: Run cargo fmt
        run: cargo make format
      - name: Run cargo clippy
        run: cargo make clippy